[package]
name = "joestar-demo"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
joestar = {  path = "../joestar" }
joestar-html = { path = "../joestar-html" }
env_logger = "0.10.0"